[package]
name = "ebnf-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
parse-hyperlinks = "0.27.2"
rangemap = "1.5.1"
lsp-server = "0.7.6"
lsp-types = "0.97.0"
serde = "1.0.130"
serde_json = "1.0.68"
ebnf-parser = "0.1.0"
ebnf-fmt = "0.1.0"
